Nasbench201 API
Multi-Objective-NAS/NAS-Bench-201 pull request #1
Opened 2020-08-08 16:11 UTC by young917

기존 nasbench 201에서 epoch에 따른 정확도(accuracy), 걸린시간, 손실(loss)가 저장되었었는데요,
정확도는 max 값으로 하나만 저장하고, 걸린시간은 sum해서 dataset/NAS-BENCH-201-v2.pth 로 저장했습니다.
여기에 추가로 손실값을 아예 없앤 것은 dataset/NAS-BENCH-201-v2-wo-losses.pth 로 저장했습니다.

이 데이터를 로드하는 함수가 nas_201_api/api_201.py 입니다.
기존과 완전히 다르게 짰으며 nas_201_api/model_spec_201.py 의 구조체를 사용하고 있습니다.

SemiNAS에서 필요한 함수를 nasbench201과 101 에서 통일해서 쓸 수 있도록 만들었고,
이에 대한 예시로 How to use를 만들어보았습니다!

2020-08-09 05:24 UTC, juice500ml requested changes
Please add command line tool for generating smaller `.pth`.
Example: https://github.com/Multi-Objective-NAS/self-supervised-nas/blob/master/datasets/nasbench/tfrecord_sampler.py

You'll have too add in the `self-supervised-nas` repo, so please add a commit ref in the issue comment section.

2020-08-23 03:37 UTC, juice500ml requested changes

2020-08-23 03:37 UTC, juice500ml commented on nas_201_api/reduce_file.py
> +from nas_201_api import NASBench201API as API
Unused import

2020-08-23 03:37 UTC, juice500ml commented on nas_201_api/reduce_file.py
> +
This file should be inside self-supervised-nas, like https://github.com/Multi-Objective-NAS/self-supervised-nas/tree/master/datasets/nasbench

2020-08-23 03:38 UTC, juice500ml commented on nas_201_api/model_spec_201.py
> +    def _convert_to_matrix_ops(self, arch_str):
You should add unittests with https://docs.python.org/3/library/unittest.html for this function!

2020-08-23 09:37 UTC, juice500ml requested changes
This PR should not be merged to `master`, as originally told. Make another branch named `self-supervised-nas`, and merge it there.

2020-08-23 09:37 UTC, juice500ml commented on nas_201_api/api_201.py
> +        self.filename = None
On normal occasions, you shouldn't do this. Is there a reason for this?

2020-08-23 09:37 UTC, juice500ml commented on nas_201_api/api_201.py
> +        self.filename = None
Is there a reason for keeping `self.filename`? It doesn't seem to be used elsewhere except initialization of `path`.

2020-08-23 09:37 UTC, juice500ml commented on nas_201_api/api_201.py
> +        self.max_edges = 0
Initializer and declaration should be together. This is not a C++ codebase.

2020-08-23 09:37 UTC, juice500ml commented on nas_201_api/api_201.py
> +            self.arch2infos_dict[archidx] = path["arch2infos"][archidx]
Why is `self.arch2infos_dict` OrderedDict? I can't see any specific reason for that. Please clarify.

2020-08-23 09:37 UTC, juice500ml commented on nas_201_api/api_201.py
> +            return False
Is this returning `False` or `model_spec`? This is quite misleading. This should be something like
```
def is_valid(self, matrix, ops):
  # Various checking procedures, may return False
  return True

def get_modelspec(self, matrix, ops):
  # If there exists a problem, it is the user's fault. Just raise exceptions and die.
  return model_spec
```

2020-08-23 09:37 UTC, juice500ml commented on nas_201_api/api_201.py
> +            return False
The `get_modelspec` function has two responsibilities, which shouldn't happen. Split responsibilities, and give adequate amount of responsibility to the already-existing `is_valid` function.

2020-08-23 09:37 UTC, juice500ml commented on nas_201_api/api_201.py
> +    """
Please do not leave code comments like this.

2020-08-23 09:37 UTC, juice500ml commented on nas_201_api/api_201.py
> +            return avg_test_acc
Why don't this raises exception if `option` parameter is wrong? Kill the program if parameters are wrong. Do not go silent!

2020-08-23 09:37 UTC, juice500ml commented on nas_201_api/api_utils.py
> +    def reset_pseudo_train_times(self, estimated_per_epoch_time: float) -> None:
Why is there duplicate codes here???

2020-08-23 09:37 UTC, juice500ml commented on nas_201_api/reduce_file.py
> +                    result['train_acc1es'] = max(result['train_acc1es'].values())
What happens if this is not a `dict` object? Why is this code necessary?

2020-08-23 09:39 UTC, juice500ml commented
`query_option` is a misnomer, as it sounds like you are querying between options. Please consider renaming it. Plain `query()` will be nicer.

2020-08-24 15:16 UTC, juice500ml requested changes

2020-08-24 15:16 UTC, juice500ml commented on nas_201_api/api_201.py
> +    # matrix, ops -> looking into all archs and find isomorphic network.
Remove comments!

2020-08-24 15:16 UTC, juice500ml commented on nas_201_api/api_201.py
> +    def query_option(self, modelspec, option, dataset='cifar10-valid'):
Why is there '-valid' when `option` parameter exists?

2020-08-24 15:16 UTC, juice500ml commented on nas_201_api/model_spec_201.py
> +class ModelSpec(object):
Nearly-the-same ModelSpec exists in `nasbench-101`. Please consider removing duplicate code.

2020-08-24 15:16 UTC, juice500ml commented on nas_201_api/reduce_file.py
> +import tqdm
Why is there two `tqdm`s? Upper import ought to be removed.

2020-08-24 15:16 UTC, juice500ml commented on nas_201_api/reduce_file.py
> +
Minor edit: indentation and spacing is somewhat awkward.

2020-08-29 08:57 UTC, young917 commented on nas_201_api/reduce_file.py
> +from nas_201_api import NASBench201API as API
없앴습니다!

2020-08-29 08:58 UTC, young917 commented on nas_201_api/reduce_file.py
> +
https://github.com/Multi-Objective-NAS/self-supervised-nas/blob/nasbench201/datasets/nasbench/reduce_file.py 이렇게 옮겼습니다

2020-08-29 09:06 UTC, young917 commented on nas_201_api/api_201.py
> +        self.filename = None
말씀해주신대로 있을 필요가 없을 것 같아서 지웠습니다.

2020-08-29 09:15 UTC, young917 commented on nas_201_api/api_201.py
> +        self.max_edges = 0
```self.total_time``` 과 ```self.total_epochs``` 는 api를 통해 architecture의 validation이나 test 결과를 호출할 때마다 실제로 필요한 training time과 epoch를 누적시키는 값입니다. 그래서 위와 같이 하지 않고 어떻게 해야할 지 모르겠습니다...

2020-08-29 09:19 UTC, young917 commented on nas_201_api/api_201.py
> +        self.max_edges = 0
```self.max_nodes``` 와 ```self.max_edges``` 는 모든 architecture 을 보면서 가장 많은 노드 개수와 간선 개수를 저장하는 것입니다.
```self.max_nodes``` 대신 ```max_nodes``` 를 0으로 초기화시켜놓고 최대값을 구한 후 ```self.max_nodes = max_nodes``` 로 하였습니다.
완전히 C++ 스타일을 벗어나 의도대로 코드 짜는 방법은 잘 모르겠습니다...

2020-08-29 09:22 UTC, young917 commented on nas_201_api/api_201.py
> +            self.arch2infos_dict[archidx] = path["arch2infos"][archidx]
저도 이유는 모르겠지만..원래 api 에서 한 자료구조를 그대로 따르기 위해 사용했습니다...!
필요가 없을 것 같은데 시간만 느려질까 싶어서 OrderedDict을 사용하지 않기로 고쳤습니다!

2020-08-29 09:45 UTC, young917 commented on nas_201_api/reduce_file.py
> +
[see this commit!](https://github.com/Multi-Objective-NAS/self-supervised-nas/pull/2/commits/b59235c7acbd14a48ea93164c032c3fe370ed844)

2020-08-29 23:04 UTC, young917 commented on nas_201_api/model_spec_201.py
> +    def _convert_to_matrix_ops(self, arch_str):
해보았습니다..! [commit](https://github.com/Multi-Objective-NAS/NAS-Bench-201/pull/1/commits/c64c32e4f45fbfc5472341e7fbaac0931463a282)

2020-08-29 23:06 UTC, young917 commented on nas_201_api/api_utils.py
> +    def reset_pseudo_train_times(self, estimated_per_epoch_time: float) -> None:
기존 api에서 사용한 파일이며 저는 ```api_utils.py```를 사용하지 않습니다...!

2020-08-29 23:09 UTC, young917 commented on nas_201_api/api_201.py
> +    def query_option(self, modelspec, option, dataset='cifar10-valid'):
nasbench 201 api는 cifar10-valid, cifar10, cifar100, imagenet 4가지에 대한 결과값을 다 저장하고 있습니다. 그래서 ```modelspec``` 에 대해 ```dataset``` 을 ```option```으로 훈련시킨 결과를 반환해주기 위해서 존재합니다...!
nasbench 101 에서는 ```dataset```을 사용하지 않기 때문에 해당 인자를 optional로 둘 수 있게 했습니다...!

2020-08-29 23:12 UTC, young917 commented on nas_201_api/model_spec_201.py
> +class ModelSpec(object):
넵!

2020-08-29 23:12 UTC, young917 commented on nas_201_api/api_201.py
> +    # matrix, ops -> looking into all archs and find isomorphic network.
네!

2020-08-29 23:15 UTC, young917 commented
> `query_option` is a misnomer, as it sounds like you are querying between options. Please consider renaming it. Plain `query()` will be nicer.

nasbench101 에 이미 query라는 함수가 있고, 이 함수를 사용하기 때문에 그랬는데요!
그래서
```query``` -> ```_query```
```query_option``` -> ```query```
로 수정해보았습니다...!

2020-08-29 23:20 UTC, young917 commented on nas_201_api/reduce_file.py
> +                    result['train_acc1es'] = max(result['train_acc1es'].values())
```original pth``` 파일에서,
```result['train_acc1es'] = { 0: 0.67, 1: 0.78, ... } ``` 와 같이 'epoch' , 'epoch 결과 정확도' 인  ```dict``` 형태인 경우도 있고
```result['train_acc1es'] = 0.89``` 와 같이 저장되어있는 경우도 존재해서 넣었습니다...!

2020-08-29 23:21 UTC, young917 commented on nas_201_api/reduce_file.py
> +import tqdm
잘못하였네요! 네!

2020-08-29 23:25 UTC, young917 commented on nas_201_api/reduce_file.py
> +
https://github.com/Multi-Objective-NAS/self-supervised-nas/blob/master/datasets/nasbench/tfrecord_sampler.py
와 똑같이 했다고 생각했는데요...! 줄 한 칸 띄는 것을 없앴습니다!

2020-08-29 23:58 UTC, young917 commented on nas_201_api/api_201.py
> +            return False
네! 잘 알겠습니다!!

2020-08-30 00:00 UTC, young917 commented on nas_201_api/api_201.py
> +            return avg_test_acc
넵! 반영해보았습니다!

2020-08-30 08:20 UTC, juice500ml commented on nas_201_api/api_utils.py
> +    def reset_pseudo_train_times(self, estimated_per_epoch_time: float) -> None:
Then plz remove unused codes!

2020-08-30 08:35 UTC, juice500ml commented on nas_201_api/model_spec_201.py
> +    def _convert_to_matrix_ops(self, arch_str):
tests should be in other file!

2020-08-30 08:35 UTC, juice500ml commented on nas_201_api/api_201.py
> +            self.arch2infos_dict[archidx] = path["arch2infos"][archidx]
Please be sure, i think there is some code that uses dict idx! (enumeration)

2020-08-30 08:36 UTC, juice500ml commented on nas_201_api/api_201.py
> +            return False
I don't think this is resolved yet!

2020-09-05 22:00 UTC, young917 commented on nas_201_api/api_utils.py
> +    def reset_pseudo_train_times(self, estimated_per_epoch_time: float) -> None:
알겠습니다!

2020-09-05 23:07 UTC, young917 commented on nas_201_api/api_201.py
> +            self.arch2infos_dict[archidx] = path["arch2infos"][archidx]
제 코드에서 볼 때는 ```self.arch2infos_dict```을 key로 접근할 때만 쓰여서 필요가 없다는 생각이 듭니다....! 기존 코드에서 OrderedDict 을 사용한 게 출력할 때의 순서를 정렬시키기 위해서로 해석되었습니다...!

2020-09-06 08:15 UTC, young917 commented on nas_201_api/api_201.py
> +            return False
```def get_modelspec(self, matrix, ops) ``` 는 아직 정말 valid 한 지 모르는 modelspec 을 반환합니다,
```def is_valid(self, modelspec)``` 은 modelspec 이 valid함을 검증하는 method로 invalid 하면 False 를 반환합니다.
그래서 ```modelspec = get_modelspec( ... )``` 후에 ```is_valid(modelspec)``` 으로 검증한 후 사용해야하는 방식으로 하였습니다.

2020-09-06 09:22 UTC, merged